
services:
  app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - BRAVE_API_KEY=${BRAVE_API_KEY}
    restart: unless-stopped
    env_file: .env
